version: "2.1"
services:
  backend:
    build: .
    ports:
      - "8200:8200"
  frontend:
    build: ./togle
    ports:
      - "8400:80"
  redis:
    image: redis:latest
    ports:
      - "6279:6379"

