# Generated by Django 5.1.1 on 2024-10-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulbState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempratureHumidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('pressure', models.CharField(max_length=100)),
                ('moisture', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
    ]
