# Generated by Django 5.1.1 on 2024-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toggle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempratureHumidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
