# Generated by Django 5.1.1 on 2024-10-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toggle', '0002_tempraturehumidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempraturehumidity',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='tempraturehumidity',
            name='temp',
        ),
    ]
